apiVersion: apps/v1
kind: Deployment
metadata:
  name: container1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container-1
  template:
    metadata:
      labels:
        app: container-1
    spec:
      containers:
        - name: container-1
          image: us-central1-docker.pkg.dev/infra-filament-387916/k8s-assignment-artifact-registery/k8s-container-1:latest
          ports:
            - containerPort: 6000
          volumeMounts:
            - name: data-volume
              mountPath: /usr/priyank_pv_dir
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: my-pvc
