steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://source.developers.google.com/p/${_PROJECT}/r/${_REPO_NAME}']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}']

  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'container2-deployment.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'

  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'container2-service.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'

options:
  substitution_option: 'ALLOW_LOOSE'
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _PROJECT: infra-filament-387916
  _ZONE: us-central1-a
  _GKE_CLUSTER: k8s-assignment
  _REPO_NAME: k8s-assignment-container2
  _CONTAINERNAME: k8s-container-2
  _VERSION: latest
