apiVersion: apps/v1
kind: Deployment
metadata:
  name: container2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container-2
  template:
    metadata:
      labels:
        app: container-2
    spec:
      containers:
        - name: container-2
          image: us-central1-docker.pkg.dev/infra-filament-387916/k8s-assignment-artifact-registery/k8s-container-2:latest
          volumeMounts:
            - name: data-volume
              mountPath: /usr/priyank_pv_dir
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: my-pvc
